import { vi } from 'vitest'

// These must be set before any module imports TOKEN_ARRAY at load time
process.env.TOKEN_ARRAY = 'BOT_TOKEN_1,BOT_TOKEN_2'
process.env.BOT_TOKEN_1 = 'fake-token-1'
process.env.BOT_TOKEN_2 = 'fake-token-2'
process.env.KCNA_BASE_URL = 'http://www.kcna.kp'
process.env.ARTICLES_COLLECTION = 'articles'
process.env.PICSETS_COLLECTION = 'picSets'
process.env.PICS_COLLECTION = 'pics'
process.env.LOG_COLLECTION = 'scrapeLog'
process.env.TG_CHANNEL_ID = '-1001234567890'
process.env.TG_MAX_LENGTH = '4096'
process.env.PIC_PATH = '/tmp/pics'
process.env.PIC_PROGRESS_SIZE = '102400'
process.env.API_PASSWORD = 'test-password'
process.env.API_SCRAPER = '/api/scrape'
process.env.SCRAPE_PORT = '1951'
process.env.SCRAPE_INTERVAL = '3600000'
